name: Codecov

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "examples/**"

  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "examples/**"

jobs:
  cover:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          check-latest: true
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run coverage
        run: go test -race -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
